In [8]:
import numpy as np

# numpy는 무조건 array...
print("numpy의 array는 동일한 타입으로만 이루어진다.")

numpy의 array는 동일한 타입으로만 이루어진다.


In [ ]:
n_size = 10
range_array = np.arange( n_size )      # 0부터 9까지 10개, array, dim 없네.
# range_array.info() # 불가 
range_array.shape                     # array의 형태. 값은 나오지만, 변하는 건 아냐.
                                      # 이것은 1차원. 그냥 array이지 행 혹은 행렬은 아님.
range_array.reshape(-1,1)             # 컬럼 1개인 벡터로 변경하는 것 처럼 보이나, 변경은 아님.
range_array.reshape(-1,1).shape       # 이렇게도 되근군. 역시 달라지는 건 아냐.
range_array.shape                     # range_array는 안 변해
b = range_array.reshape(-1,1)         # 형태를 바꿔 n by 1으로 받으려면 새로운 변수 지정.
b.shape                               # 별도 이름을 줘야 변함.

con_array = np.ones( n_size )         # 1로 이루어진 array,  
con_array.shape
c = con_array.reshape(-1,1)           # ndarray n by 1

X = np.c_[c, b]                       # ndarray n by 2, 열 벡터 사이드 바이 사이드 합쳐 행렬로.
X.shape

Xb = np.concatenate((c, b), axis=0)    # 아래로 합치기, 벡터 위 - 아래 쌓기로 행렬. 2n by 1 
Xb.shape 

Xc = np.concatenate((c, b), axis=1)    # 옆으로 합치기, 사이드 바이 사이드, 행렬. n by 2
Xc.shape 



[[1. 0.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]
 [1. 7.]
 [1. 8.]
 [1. 9.]]


In [25]:
X.ndim                                  # 축 수가 뭐지. 위에 axis = 0, 1 여기에 들어가는 것이구만. 
X.size                                  # 배열의 요소 수. 그러니까 10 by 2, 20. 이렇게 됨.
X.shape                                 # (행, 열) 수 
TX = X.reshape(-1, 4)                   # 행 요소 순서대로 차곡차곡 나열. 단, 열의 갯수 4. 이런 식으로. 
print(X, "\n" , TX) 

## 축이 3개, 그 이상일 수 있는데, 그걸 tensor 이렇게 하네...
## 엑셀 시트(2축) -> 시트 여러 개(3축) -> 파일 여러 개(4축) -> 폴더 여러개(5축) ... 이런 식으로. 이미지 형성.
## ndarray는 이런 식으로 데이터를 다룬다는 것. 직관 이해는 불가.
## 연산은? 
## 예) Kronecker product, 크로네커 곱, 이게 4차원인 셈.
## A (x) B ==> A 각 원소(i,j)에 B를 모두 곱한다는 것(k,l) 

# 축에 들어 있는 정보는 순서상 행->열인 모양.
print("행 수, 열 수:", TX.shape[0], TX.shape[1])



[[1. 0.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]
 [1. 7.]
 [1. 8.]
 [1. 9.]] 
 [[1. 0. 1. 1.]
 [1. 2. 1. 3.]
 [1. 4. 1. 5.]
 [1. 6. 1. 7.]
 [1. 8. 1. 9.]]
행 수, 열 수: 5 4


In [ ]:
# 데이서 생성 후 연습하자. 
# rng.random np.random.normal(loc=100, scale=15, size=n_pop)
SEED = 135678942
ARRAY_SIZE = 73


def generate_data(seed, array_size):
    """배열 v, w, x, y를 생성합니다."""
    rng = np.random.default_rng(seed)

    # v: 인덱스 (0 ~ 999)
    v = np.arange(ARRAY_SIZE)
    
    # w: 1/3은 0, 2/3은 1
    w = np.zeros(ARRAY_SIZE)
    w[ARRAY_SIZE // 3:] = 1
    rng.shuffle(w)  # 섞기
    
    # x: 평균 100, 표준편차 15인 난수
    x = rng.normal(loc=100, scale=15, size=ARRAY_SIZE)
 